In [1]:
import sys
import argparse
import os
sys.path.append(os.path.expanduser("~/websites/mapedia"))
from modules import DBHandler, DBUpdater
import pandas as pd
import numpy as np
from modules.db_handler.DBConfig import INTER_CITY_LEARNING_SOURCE, INTRA_CITY_LEARNING_SOURCE, EMPTY_SOURCE
INTRA_CITY_LEARNING_PRESET_CONFIDENCE = 0.8

In [2]:
metadata_path  = os.path.join('./data/imputed_data/', f"jakarta_imputedBy_jakarta.parquet")
metadata = pd.read_parquet(metadata_path)
metadata.head()

,idx,source,target,mapd_id,pgr_id,osm_id,oneway,road_type,nlanes,width,...,imputed_avg_speed_weekend_08-12,avg_speed_weekend_12-16,pred_avg_speed_weekend_12-16,imputed_avg_speed_weekend_12-16,avg_speed_weekend_16-20,pred_avg_speed_weekend_16-20,imputed_avg_speed_weekend_16-20,avg_speed_weekend_20-24,pred_avg_speed_weekend_20-24,imputed_avg_speed_weekend_20-24
0,0,52860,7874,282664,98,4705045,1.0,2.0,4.0,10.0,...,8.897243,8.955077,41.415527,8.955077,11.846818,48.392166,11.846818,5.271908,46.888874,5.271908
1,1,30445,87959,282663,212,4705043,1.0,2.0,1.0,4.0,...,7.279488,7.610105,22.801670,7.610105,11.480000,24.459898,11.480000,9.215501,24.294548,9.215501
2,2,1359,102290,282665,213,4705046,1.0,2.0,2.0,6.0,...,8.752268,9.169477,28.757809,9.169477,12.175380,31.591429,12.175380,15.253763,31.416620,15.253763
3,3,47817,58347,282665,38783,4705046,1.0,2.0,2.0,6.0,...,8.752268,9.169477,42.240459,9.169477,12.175380,46.035675,12.175380,15.253763,48.690834,15.253763
4,4,7874,92444,282664,47381,4705045,1.0,2.0,4.0,10.0,...,8.897243,8.955077,35.345345,8.955077,11.846818,39.710392,11.846818,5.271908,39.743553,5.271908

In [3]:
metadata.columns

Index(['idx', 'source', 'target', 'mapd_id', 'pgr_id', 'osm_id', 'oneway',
       'road_type', 'nlanes', 'width', 'length', 'geometry', 'max_speed',
       'min_speed', 'nlanes_cls', 'highway_id', 'pred_road_type',
       'pred_nlanes_cls', 'pred_oneway', 'pred_width', 'pred_max_speed',
       'pred_min_speed', 'imputed_road_type', 'imputed_nlanes_cls',
       'imputed_oneway', 'imputed_width', 'imputed_max_speed',
       'imputed_min_speed', 'avg_speed_weekday_00-04',
       'pred_avg_speed_weekday_00-04', 'imputed_avg_speed_weekday_00-04',
       'avg_speed_weekday_04-08', 'pred_avg_speed_weekday_04-08',
       'imputed_avg_speed_weekday_04-08', 'avg_speed_weekday_08-12',
       'pred_avg_speed_weekday_08-12', 'imputed_avg_speed_weekday_08-12',
       'avg_speed_weekday_12-16', 'pred_avg_speed_weekday_12-16',
       'imputed_avg_speed_weekday_12-16', 'avg_speed_weekday_16-20',
       'pred_avg_speed_weekday_16-20', 'imputed_avg_speed_weekday_16-20',
       'avg_speed_weekday_20-24', 'pred_avg_speed_weekday_20-24',
       'imputed_avg_speed_weekday_20-24', 'avg_speed_weekend_00-04',
       'pred_avg_speed_weekend_00-04', 'imputed_avg_speed_weekend_00-04',
       'avg_speed_weekend_04-08', 'pred_avg_speed_weekend_04-08',
       'imputed_avg_speed_weekend_04-08', 'avg_speed_weekend_08-12',
       'pred_avg_speed_weekend_08-12', 'imputed_avg_speed_weekend_08-12',
       'avg_speed_weekend_12-16', 'pred_avg_speed_weekend_12-16',
       'imputed_avg_speed_weekend_12-16', 'avg_speed_weekend_16-20',
       'pred_avg_speed_weekend_16-20', 'imputed_avg_speed_weekend_16-20',
       'avg_speed_weekend_20-24', 'pred_avg_speed_weekend_20-24',
       'imputed_avg_speed_weekend_20-24'],
      dtype='object')

In [4]:
pred_metadata = metadata[['mapd_id', 'osm_id',
        'pred_road_type', 'pred_nlanes_cls',
       'pred_oneway', 'pred_width', 'pred_max_speed', 'pred_min_speed']].copy()
pred_metadata.rename(columns={
    'pred_road_type': 'road_type', 
    'pred_nlanes_cls': 'nlanes',
    'pred_oneway': 'oneway', 
    'pred_width': 'width', 
    'pred_max_speed': 'max_speed', 
    'pred_min_speed': 'min_speed'
}, inplace=True)

In [5]:
for c in ['road_type', 'nlanes', 'oneway', 'width', 'max_speed', 'min_speed']:
    pred_metadata[f'{c}_source'] = INTRA_CITY_LEARNING_SOURCE
    pred_metadata[f'{c}_conf'] = INTRA_CITY_LEARNING_PRESET_CONFIDENCE

In [6]:
speed_metadata = metadata[['mapd_id', 'osm_id',
       'pred_avg_speed_weekday_00-04',
       'pred_avg_speed_weekday_04-08',
       'pred_avg_speed_weekday_08-12',
       'pred_avg_speed_weekday_12-16',
       'pred_avg_speed_weekday_16-20',
       'pred_avg_speed_weekday_20-24',
       'pred_avg_speed_weekend_00-04',
       'pred_avg_speed_weekend_04-08',
       'pred_avg_speed_weekend_08-12',
       'pred_avg_speed_weekend_12-16',
       'pred_avg_speed_weekend_16-20',
       'pred_avg_speed_weekend_20-24']].copy()

In [7]:
# Period label → (start_hour, end_hour)
PERIOD_HOURS = {
    "00-04": range(0, 4),
    "04-08": range(4, 8),
    "08-12": range(8, 12),
    "12-16": range(12, 16),
    "16-20": range(16, 20),
    "20-24": range(20, 24),
}

# weekday=0 means Monday in pandas; 0-4 = weekday, 5-6 = weekend
WEEKDAY_DAYS = list(range(5))   # 0-4
WEEKEND_DAYS = list(range(5, 7)) # 5-6

# 1. One period-block: 6 periods × their hour counts = 24 values
#    Each period value repeated for its hours
period_cols_weekday = [f"pred_avg_speed_weekday_{p}" for p in PERIOD_HOURS]
period_cols_weekend = [f"pred_avg_speed_weekend_{p}" for p in PERIOD_HOURS]
period_lengths      = [len(h) for h in PERIOD_HOURS.values()]  # [4,4,4,4,4,4]

def build_day_vector(row, cols):
    """24 values: each period value repeated for its hour count"""
    return np.repeat([row[c] for c in cols], period_lengths)  # (24,)

def build_week_vector(row):
    """168 values: 5× weekday-day + 2× weekend-day"""
    day = build_day_vector(row, period_cols_weekday)  # (24,)
    end = build_day_vector(row, period_cols_weekend)  # (24,)
    return np.concatenate([np.tile(day, 5), np.tile(end, 2)])  # (168,)

def build_speed_array(row):
    """672 values: week vector repeated 4× for seasons"""
    return np.tile(build_week_vector(row), 4)  # (672,)

# Apply once per road
speed_matrix = np.stack(speed_metadata.apply(build_speed_array, axis=1))  # (N, 672)

In [8]:
speed_matrix_source = np.full(speed_matrix.shape, INTRA_CITY_LEARNING_SOURCE, dtype=np.float32)
speed_matrix_source[np.isnan(speed_matrix)] = np.nan
speed_matrix_conf   = np.full(speed_matrix.shape, INTRA_CITY_LEARNING_PRESET_CONFIDENCE, dtype=np.float32)
speed_matrix_conf[np.isnan(speed_matrix)] = np.nan

ordered_ids = pred_metadata.mapd_id.to_numpy()

In [9]:
db_handler = DBHandler()
db_handler.connect_to_db()
road_attributes = db_handler.roads_from_ids(ordered_ids.tolist())

In [10]:
road_attr = road_attributes.loc[ordered_ids]
old_val = np.array(road_attr["avg_speed"].tolist(), dtype=np.float32)
old_source = np.array(road_attr["avg_speed_source"].tolist(), dtype=np.float32)
old_conf = np.array(road_attr["avg_speed_conf"].tolist(), dtype=np.float32)

In [11]:
new_val = speed_matrix
new_source = speed_matrix_source
new_conf = speed_matrix_conf

In [12]:
import numpy as np
import pandas as pd

# def convert_to_matricies(dynamic_pred_metadata, road_attributes):
#     print('1. Align the DataFrames by ID so the matrix rows match perfectly')
#     shared_ids = dynamic_pred_metadata.index
#     road_attr_subset = road_attributes.loc[shared_ids]

#     print('2. Extract entire columns into 2D NumPy arrays')
#     # Each resulting array will have a shape of (num_rows, 672)
#     old_val = np.stack(road_attr_subset['avg_speed'].values)
#     old_source = np.stack(road_attr_subset['avg_speed_source'].values)
#     old_conf = np.stack(road_attr_subset['avg_speed_conf'].values)

#     new_val = np.stack(dynamic_pred_metadata['avg_speed'].values)
#     new_source = np.stack(dynamic_pred_metadata['avg_speed_source'].values)
#     new_conf = np.stack(dynamic_pred_metadata['avg_speed_conf'].values)
    
#     return old_val, old_source, old_conf, new_val, new_source, new_conf

def update_old_vals(old_val, old_source, old_conf, new_val, new_source, new_conf):
    print('3. Compute the boolean mask across the entire 2D grid instantly')
    empty_old_val = np.isnan(old_val)
    better_source = new_source < old_source
    same_source_better_conf = (new_source == old_source) & (new_conf >= old_conf)

    # Combine conditions into a single master mask
    mask = empty_old_val | better_source | same_source_better_conf

    print('4. Apply changes to the arrays in-place where the mask is True')
    old_val[mask] = new_val[mask]
    old_source[mask] = new_source[mask]
    old_conf[mask] = new_conf[mask]
    
    return old_val, old_source, old_conf

db_handler = DBHandler()
db_handler.connect_to_db()
# update_road_ids = dynamic_pred_metadata.index.tolist()
# road_attributes = db_handler.roads_from_ids(update_road_ids)
# old_val, old_source, old_conf, new_val, new_source, new_conf = convert_to_matricies(dynamic_pred_metadata, road_attributes)
val, source, conf = update_old_vals(old_val, old_source, old_conf, new_val, new_source, new_conf)

3. Compute the boolean mask across the entire 2D grid instantly
4. Apply changes to the arrays in-place where the mask is True

In [13]:
import psycopg2

def connect_to_db_psycopg2():
    """Initializes a pure psycopg2 connection if it doesn't exist."""
    conn = psycopg2.connect(
        "postgresql://gis:gis@cs-u-spatial-406.cs.umn.edu:5432/gis"
    )
    return conn
conn = connect_to_db_psycopg2()

In [ ]:
db_updater = DBUpdater(db_handler)

In [50]:
from tqdm import tqdm
import io

# 2. Set Up Chunking
print('Set Up Chunking')
# Over 1 billion array elements will cause RAM bloat if written to a single stream.
chunk_size = 50000
total_rows = len(ordered_ids)

# Open a single cursozr context manager
with conn.cursor() as cur:

    # 3. Create High-Performance UNLOGGED Staging Table
    print('Create High-Performance UNLOGGED Staging Table')
    # ON COMMIT DROP is replaced with manual dropping since pure psycopg2 transactions vary
    cur.execute("""
        DROP TABLE IF EXISTS tmp_road_update;
        CREATE UNLOGGED TABLE tmp_road_update (
            id bigint,
            avg_speed numeric[],
            avg_speed_source integer[],
            avg_speed_conf double precision[]
        );
    """)

    # 4. Stream Data in Chunks
    print('Stream Data in Chunks')
    for i in range(0, total_rows, chunk_size):
        end_idx = min(i + chunk_size, total_rows)

        buffer = io.StringIO()

        # Fast string formatting loop for the active chunk
        for j in tqdm(range(i, end_idx), total=(end_idx-i), desc=f'Processing Chunk{i}'):
            # Format into native PostgreSQL text array strings: {val1,val2,val3}
            # print('pgspeed conversion to string')
            pg_speed = (
                str(speed_matrix[j].tolist())
                .replace("[", "{")
                .replace("]", "}")
            )
            # print('pgconf to string')
            pg_conf = (
                str(speed_matrix_conf[j].tolist())
                .replace("[", "{")
                .replace("]", "}")
            )

            # For the integer array, we safely cast numbers to int if they aren't NaN.
            # Keeping them as "nan" maps safely to database NULLs later.
            # print('pgsource to string')
            pg_source = (
                "{"
                + ",".join(
                    [
                        str(int(x)) if not np.isnan(x) else "nan"
                        for x in speed_matrix_source[j]
                    ]
                )
                + "}"
            )

            # Write tab-separated row straight to memory buffer
            # print('writing to buffer')
            buffer.write(
                f"{int(ordered_ids[j])}\t{pg_speed}\t{pg_source}\t{pg_conf}\n"
            )

        buffer.seek(0)

        # Stream data chunk straight into the staging table bypassing SQL engine parsing
        print('Copying from the buffer to the table directly')
        cur.copy_from(
            buffer,
            "tmp_road_update",
            columns=("id", "avg_speed", "avg_speed_source", "avg_speed_conf"),
            null="NULL",
        )
        buffer.close()

    # 5. Index the Staging Table
    # Speeds up the final JOIN execution on 500,000 rows drastically.
    print('Creating Index on the temp_road_update')
    cur.execute("CREATE INDEX idx_tmp_road_id ON tmp_road_update(id);")

    # 6. Execute Single Native Bulk Update Join
    print('Execute Update Join')
    cur.execute("""
        UPDATE road_attributes r
        SET 
            avg_speed = t.avg_speed,
            avg_speed_source = t.avg_speed_source,
            avg_speed_conf = t.avg_speed_conf
        FROM tmp_road_update t
        WHERE r.id = t.id
    """)

    # 7. Cleanup Staging Table
    print('Droping the newly created table')
    cur.execute("DROP TABLE tmp_road_update;")

    # Commit everything to the database at once
    print('Commiting')
    conn.commit()

Set Up Chunking
Create High-Performance UNLOGGED Staging Table
Stream Data in Chunks

Processing Chunk0: 100%|██████████| 50000/50000 [01:00<00:00, 824.87it/s]

Copying from the buffer to the table directly

Processing Chunk50000: 100%|██████████| 50000/50000 [01:00<00:00, 825.72it/s]

Copying from the buffer to the table directly

Processing Chunk100000: 100%|██████████| 50000/50000 [01:00<00:00, 828.78it/s]

Copying from the buffer to the table directly

Processing Chunk150000: 100%|██████████| 50000/50000 [01:00<00:00, 831.61it/s]

Copying from the buffer to the table directly

Processing Chunk200000: 100%|██████████| 50000/50000 [01:00<00:00, 830.52it/s]

Copying from the buffer to the table directly

Processing Chunk250000: 100%|██████████| 50000/50000 [01:00<00:00, 831.22it/s]

Copying from the buffer to the table directly

Processing Chunk300000: 100%|██████████| 50000/50000 [01:00<00:00, 825.98it/s]

Copying from the buffer to the table directly

Processing Chunk350000: 100%|██████████| 50000/50000 [01:00<00:00, 827.89it/s]

Copying from the buffer to the table directly

Processing Chunk400000: 100%|██████████| 50000/50000 [01:00<00:00, 832.19it/s]

Copying from the buffer to the table directly

Processing Chunk450000: 100%|██████████| 50000/50000 [01:00<00:00, 820.97it/s]

Copying from the buffer to the table directly

Processing Chunk500000: 100%|██████████| 12991/12991 [00:15<00:00, 820.38it/s]

Copying from the buffer to the table directly
Creating Index on the temp_road_update
Execute Update Join
Droping the newly created table
Commiting

In [51]:
import io
import pandas as pd
import numpy as np

# Helper function to convert a 1D row array into a Postgres array string '{1,2,3}'
# This bypasses the slow loop by executing over the rows much faster
def format_pg_array(arr):
    # If it's a float array with NaNs, handle NaNs by replacing them with 'NULL'
    if np.issubdtype(arr.dtype, np.floating):
        # Format floats, replacing nan with NULL (Postgres-friendly)
        items = [str(int(x)) if not np.isnan(x) else 'NULL' for x in arr]
    else:
        items = [str(x) for x in arr]
    return "{" + ",".join(items) + "}"

# Vectorize the helper function so it executes via fast internal loops
v_format_pg_array = np.vectorize(format_pg_array, otypes=[object])

print("Vectorizing NumPy arrays...")
# 1. Convert whole matrices into arrays of Postgres strings instantly
# This applies the function across the rows without a manual Python loop
pg_speed_col = [format_pg_array(row) for row in speed_matrix]
pg_conf_col = [format_pg_array(row) for row in speed_matrix_conf]
pg_source_col = [format_pg_array(row) for row in speed_matrix_source]

# 2. Pack everything into a Pandas DataFrame
df = pd.DataFrame({
    'id': ordered_ids.astype(int),
    'speed': pg_speed_col,
    'source': pg_source_col,
    'conf': pg_conf_col
})

print("Writing entire dataset directly to in-memory buffer...")
buffer = io.StringIO()

# 3. Use Pandas' native C-optimized engine to write tab-separated format
# 'header=False' and 'index=False' mimics exactly what your buffer.write did
df.to_csv(buffer, sep='\t', header=False, index=False)
buffer.seek(0)

print("Done! Buffer is ready to be streamed via COPY.")

Vectorizing NumPy arrays...
Writing entire dataset directly to in-memory buffer...
Done! Buffer is ready to be streamed via COPY.

In [ ]:

    def update_dynamic_attributes(
        self, speed_matrix, source_matrix, conf_matrix, id_list
    ):
        # Ensure database connection is alive
        print('Connecting to Database using psycopg2')
        self.connect_to_db_psycopg2()

        # # 1. Fast Vectorized NaN Pre-processing using NumPy
        # print('Fast Vectorized NaN Pre-processing using NumPy')
        # # Replaces slow element-by-element Python scalar loops.
        # # PostgreSQL COPY reads 'NULL' (without quotes) as a database NULL inside arrays.
        # speed_clean = np.where(np.isnan(speed_matrix), "NULL", speed_matrix)
        # conf_clean = np.where(np.isnan(conf_matrix), "NULL", conf_matrix)
        # source_clean = np.where(
        #     np.isnan(source_matrix), "NULL", source_matrix.astype(object)
        # )

In [23]:
road_attr = road_attributes.loc[ordered_ids]
road_attr['avg_speed']

282664       [None, None, None, None, None, None, None, Non...
282663       [None, None, None, None, None, None, None, Non...
282665       [None, None, None, None, None, None, None, Non...
282665       [None, None, None, None, None, None, None, Non...
282664       [None, None, None, None, None, None, None, Non...
                                   ...
212245832    [None, None, None, None, None, None, None, Non...
211625167    [None, None, None, None, None, None, None, Non...
211603264    [None, None, None, None, None, None, None, Non...
211553340    [None, None, None, None, None, None, None, Non...
211358975    [None, None, None, None, None, None, None, Non...
Name: avg_speed, Length: 512991, dtype: object

In [24]:
road_attr['avg_speed'].values

array([list([None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, Decimal('9.52993076122449'), Decimal('8.713604350016404'), Decimal('9.595946087894113'), None, Decimal('9.252570646833147'), None, None, None, Decimal('10.389615522531361'), Decimal('7.957000000000001'), Decimal('7.242214'), Decimal('8.579424634251241'), None, Decimal('10.245714285714286'), Decimal('10.430869517119035'), Decimal('12.448333333333332'), None, None, None, None, Decimal('11.817777777777778'), None, None, Decimal('10.472500085830688'), Decimal('9.109925171887433'), Decimal('10.50179537646274'), Decimal('8.107272624969482'), Decimal('10.87142857142857'), Decimal('4.523651411764706'), Decimal('11.173076923076923'), Decimal('9.652666439999999'), Decimal('10.791851851851852'), Decimal('10.163242883682251'), Decimal('8.853928571428572'), Decimal('9.006978324053955'), Decimal('11.029999666666667'), Decimal('10.862'), None, Decimal('11.149999904632569'), Decimal('11.163849081984576'), None, None, None, None, None, None, None, Decimal('9.294374942779541'), Decimal('10.378812838235294'), Decimal('9.345000147819519'), Decimal('11.499999926640438'), Decimal('10.64097892567359'), Decimal('17.06555567847358'), Decimal('12.621141624450683'), None, Decimal('9.547646766666666'), Decimal('14.722500085830688'), Decimal('8.765624964776357'), Decimal('8.353333393732706'), None, Decimal('9.26908302173913'), Decimal('10.575555483500164'), None, Decimal('11.083478222722592'), Decimal('10.862307695242075'), None, None, None, None, None, Decimal('9.077016227520534'), Decimal('11.199047662644158'), Decimal('7.809028979976654'), None, Decimal('6.6379999876022335'), Decimal('11.222692342904898'), Decimal('7.765882352941177'), None, Decimal('11.625217313351838'), Decimal('8.296734686092455'), Decimal('8.01894922090867'), Decimal('4.389039153925863'), Decimal('9.543000022888183'), Decimal('7.589385170172214'), Decimal('9.104615431565504'), Decimal('0.6154566216577678'), Decimal('7.764163817284342'), None, None, None, None, None, None, None, None, Decimal('9.81440005493164'), None, None, Decimal('9.556800022125245'), Decimal('7.897777822282579'), Decimal('14.066758125'), Decimal('11.207611548540388'), Decimal('4.0444387196948846'), Decimal('8.57075688065389'), None, Decimal('7.628628999762432'), Decimal('6.438518349822574'), Decimal('8.599069755909055'), Decimal('9.150980366351558'), None, None, None, None, None, None, None, None, None, Decimal('11.58'), None, None, Decimal('11.67142915725708'), Decimal('10.187905041214556'), None, Decimal('11.021428571428572'), None, Decimal('9.793581027685983'), Decimal('9.837961685823755'), Decimal('7.076394910782296'), Decimal('8.452650867684152'), Decimal('8.155977317647059'), None, Decimal('4.103606877595726'), Decimal('8.81741936837473'), Decimal('11.483353181318803'), None, None, None, Decimal('11.492727366360752'), None, None, None, None, Decimal('11.681268168148643'), None, None, Decimal('8.634980495582193'), Decimal('0.2334765573359375'), Decimal('9.936499987602234'), Decimal('9.45621132850647'), Decimal('10.320714285714287'), Decimal('10.367358445632645'), Decimal('11.09769117143419'), None, Decimal('10.21407992828139'), Decimal('8.864247935714285'), Decimal('9.051333333333334'), Decimal('7.6387499670187635'), Decimal('12.635999965667725'), None, Decimal('12.200909094376998'), None, None, None, Decimal('-1.0'), None, None, Decimal('11.406363660638982'), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]),
       list([None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, Decimal('3.3793486407317075'), Decimal('2.535372015608993'), Decimal('6.6084848606225215'), Decimal('5.102894732434499'), Decimal('3.8332224385542166'), Decimal('2.9362037054145778'), Decimal('2.6276467367196865'), Decimal('5.250526337247146'), Decimal('3.7902438934934817'), Decimal('3.02247301359375'), None, None, Decimal('8.90035582'), None, None, Decimal('10.681999719999999'), None, None, None, None, None, None, None, None, Decimal('11.2696'), Decimal('1.746701830212766'), Decimal('2.7762169254639177'), Decimal('3.124610058610635'), Decimal('6.484999999999999'), Decimal('5.720000012715658'), Decimal('5.888421058654785'), Decimal('4.271117085384615'), None, Decimal('6.934831430272358'), None, Decimal('8.806315773411802'), None, Decimal('6.878072483333333'), Decimal('10.544090899554165'), None, None, None, None, None, None, None, None, None, None, Decimal('4.044000053405762'), Decimal('3.4798205734801133'), None, Decimal('3.800681823356585'), Decimal('6.396000009775162'), None, None, Decimal('7.738854139544192'), Decimal('11.487391056521739'), Decimal('10.6812705'), Decimal('6.100108695652175'), None, None, Decimal('9.058729762962962'), Decimal('8.39705601784528'), Decimal('11.03473677133259'), None, None, None, None, None, None, None, Decimal('2.8388960811111112'), Decimal('3.059594872348528'), Decimal('6.155490190775703'), Decimal('2.6631249971687794'), Decimal('4.362322583748448'), Decimal('5.459019607843138'), None, Decimal('8.638214285714286'), Decimal('6.374235959855662'), Decimal('4.404611936190476'), Decimal('4.4634782542353095'), Decimal('6.169310419908867'), Decimal('7.38825579266527'), Decimal('5.289810455769231'), None, None, None, None, Decimal('12.50414698'), None, None, None, None, None, Decimal('8.120166670779387'), Decimal('6.19680815'), Decimal('7.036892420335736'), Decimal('8.57344818526301'), Decimal('3.9597232345864666'), None, Decimal('4.047633297310825'), Decimal('4.9275000023841855'), None, None, None, Decimal('5.567954527248036'), Decimal('8.301923107069273'), None, Decimal('9.566588925925927'), None, None, Decimal('11.52999973297119'), None, None, None, Decimal('6.757777777777778'), None, None, None, Decimal('4.731785613571428'), Decimal('6.622222191757626'), Decimal('4.799440559440559'), Decimal('6.039999993826662'), Decimal('12.857761'), Decimal('4.761707319973445'), Decimal('8.070694237183302'), Decimal('8.314711567602659'), Decimal('9.615166421568627'), None, Decimal('6.0099414'), Decimal('5.2875'), None, Decimal('8.745517138777108'), Decimal('8.6649999777476'), Decimal('11.47999954223633'), None, None, None, None, Decimal('9.141001812903225'), None, None, Decimal('9.99448275862069'), None, Decimal('5.4490322086118885'), Decimal('3.016811581884058'), None, Decimal('5.183349956603774'), Decimal('6.699714285986764'), None, Decimal('5.459375042468309'), Decimal('5.6691504'), Decimal('7.223294899999999'), Decimal('8.720967785004646'), None, Decimal('7.742400016784668'), None, None, None, None, None, None, None, None, None, Decimal('9.289999949304681'), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]),
       list([None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, Decimal('9.253784048453609'), Decimal('9.251548832268595'), Decimal('11.186475985013688'), Decimal('9.70166673262914'), Decimal('8.94123605505618'), Decimal('10.60416670454873'), Decimal('10.073026434658527'), Decimal('10.980384569901686'), None, Decimal('9.80992552'), Decimal('9.281817731372549'), None, None, Decimal('9.76024395082055'), None, None, None, None, None, Decimal('12.3837015'), None, None, None, None, Decimal('9.987875459080541'), Decimal('9.174050644615384'), Decimal('8.9979277515625'), Decimal('9.15338701407814'), Decimal('9.06646144'), None, Decimal('10.31678571019854'), Decimal('10.832231467853893'), Decimal('10.109199924468996'), Decimal('7.642594370990992'), Decimal('5.517066271428571'), Decimal('9.434979275340549'), Decimal('7.671666669845581'), Decimal('10.93173070687514'), Decimal('12.863500046730042'), None, None, Decimal('10.740952355521065'), None, None, None, None, None, None, Decimal('4.045'), Decimal('10.967173928799836'), Decimal('10.03189220877193'), Decimal('6.800999949872494'), Decimal('10.058428567886352'), Decimal('11.929841227455745'), None, Decimal('11.559509190476192'), Decimal('10.18180717944917'), Decimal('4.239999771118164'), Decimal('10.806310942307693'), Decimal('11.41029247368421'), Decimal('8.305416663487753'), None, Decimal('10.120333353678385'), Decimal('10.434861431481481'), Decimal('14.465454708446156'), None, None, None, None, None, None, Decimal('7.379642861230033'), Decimal('8.915100893031832'), Decimal('10.968816576923077'), Decimal('8.947457509753882'), Decimal('9.352666680018107'), Decimal('9.445056213421768'), Decimal('11.564074074074075'), Decimal('6.412133318710327'), Decimal('11.311707358011386'), Decimal('12.556713'), Decimal('9.19874114110039'), Decimal('9.986767689675995'), Decimal('1.8606695899011176'), Decimal('9.850781237662337'), None, Decimal('11.296399955749513'), None, None, None, None, None, None, None, None, None, Decimal('11.083038016210628'), Decimal('13.072272734208541'), Decimal('10.10214284488133'), Decimal('-1.0'), Decimal('8.87636364590038'), None, Decimal('10.275392843619079'), Decimal('7.946923109201284'), Decimal('6.542058823529412'), Decimal('11.22083330154419'), Decimal('9.796206631034483'), Decimal('10.626800041198731'), Decimal('8.11909091385928'), Decimal('8.416388686111112'), Decimal('12.0229675'), None, None, None, None, None, None, Decimal('14.224761904761904'), Decimal('10.439642857142857'), None, None, None, Decimal('9.254827573381622'), Decimal('10.399791666666667'), Decimal('10.778313291848423'), None, Decimal('10.065101400962375'), Decimal('10.4059999710083'), Decimal('11.463760768367399'), Decimal('6.61'), Decimal('3.64069535'), Decimal('7.213608239130435'), Decimal('7.89514285496303'), Decimal('7.06'), Decimal('9.195312552154064'), Decimal('9.15482757831442'), None, None, None, None, None, Decimal('15.253762882352941'), None, None, Decimal('10.371785714285716'), None, None, Decimal('4.403636363275123'), None, Decimal('5.2786506307692305'), Decimal('9.711774212698783'), Decimal('11.8447671'), Decimal('11.759999809523809'), None, Decimal('10.132413613793103'), Decimal('12.587666355289626'), None, Decimal('9.676896604998358'), None, Decimal('13.283181819048794'), Decimal('12.337142853509812'), Decimal('12.013617003014748'), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]),
       ...,

In [27]:
old_val = np.stack(road_attr['avg_speed'].values, dtype=np.float32)

TypeError: Cannot cast array data from dtype('O') to dtype('float32') according to the rule 'same_kind'

In [26]:
old_val

array([[None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None],
       ...,
       [None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None]], dtype=object)

In [ ]:

print('2. Extract entire columns into 2D NumPy arrays')
# Each resulting array will have a shape of (num_rows, 672)
old_val = np.stack(road_attr['avg_speed'].values)
old_source = np.stack(road_attr['avg_speed_source'].values)
old_conf = np.stack(road_attr['avg_speed_conf'].values)

In [ ]:
old_val = np.array(db_updater.road_attributes.loc[id].avg_speed, dtype=float)
old_source = np.array(db_updater.road_attributes.loc[id].avg_speed_source, dtype=float)
old_conf = np.array(db_updater.road_attributes.loc[id].avg_speed_conf, dtype=float)

In [8]:
pred_metadata["avg_speed"] = list(speed_matrix)
pred_metadata["avg_speed_source"] = [np.full(672, INTRA_CITY_LEARNING_SOURCE, dtype=object)] * len(pred_metadata)
pred_metadata["avg_speed_conf"]   = list(np.full((len(pred_metadata), 672), INTRA_CITY_LEARNING_PRESET_CONFIDENCE, dtype=np.float32))
dynamic_pred_metadata = pred_metadata[['mapd_id', 'osm_id', 'avg_speed', 'avg_speed_source', 'avg_speed_conf']].copy()
static_pred_metadata = pred_metadata.drop(columns=['avg_speed', 'avg_speed_source', 'avg_speed_conf'])

In [9]:
dynamic_pred_metadata = dynamic_pred_metadata.set_index("mapd_id").rename_axis(None)
static_pred_metadata = static_pred_metadata.set_index("mapd_id").rename_axis(None)

In [10]:
dynamic_pred_metadata.shape

(512991, 4)

In [ ]:
road_attributes = db_updater.road_attributes
def update_temporal_attributes_new(row):
    id = row.name
    old_row = road_attributes.loc[id]

    for col in ['avg_speed']:
        old_val    = old_row[col]
        old_source = old_row[f"{col}_source"]
        old_conf   = old_row[f"{col}_conf"]

        new_val    = row[col]                   # already (672,)
        new_source = row[f"{col}_source"]
        new_conf   = row[f"{col}_conf"]

        empty_old_val = np.isnan(old_val)
        better_source = (new_source < old_source)
        same_source_better_conf = (new_source == old_source) & (new_conf >= old_conf)
        mask = empty_old_val | better_source | same_source_better_conf

        old_val[mask]    = new_val[mask]
        old_source[mask] = new_source[mask]
        old_conf[mask]   = new_conf[mask]

    road_attributes.loc[id] = old_row

tqdm.pandas(desc="Updating temporal road attributes")
dynamic_pred_metadata.progress_apply(update_temporal_attributes_new, axis=1)

In [81]:
id = dynamic_pred_metadata.iloc[0].name
new_source = dynamic_pred_metadata.iloc[0].avg_speed_source.astype(float)
new_conf = dynamic_pred_metadata.iloc[0].avg_speed_conf.astype(float)
new_val = dynamic_pred_metadata.iloc[0].avg_speed

In [82]:
old_val = np.array(db_updater.road_attributes.loc[id].avg_speed, dtype=float)
old_source = np.array(db_updater.road_attributes.loc[id].avg_speed_source, dtype=float)
old_conf = np.array(db_updater.road_attributes.loc[id].avg_speed_conf, dtype=float)

In [ ]:
new_source = dynamic_pred_metadata.iloc[0].avg_speed_source.astype(float)
new_conf = dynamic_pred_metadata.iloc[0].avg_speed_conf.astype(float)
new_val = dynamic_pred_metadata.iloc[0].avg_speed

In [ ]:
db_updater.road_attributes.avg_speed_source.apply(lambda x: np.array(x, dtype=float))

In [ ]:
new_source = dynamic_pred_metadata.iloc[0].avg_speed_source.astype(float)
new_conf = dynamic_pred_metadata.iloc[0].avg_speed_conf.astype(float)

In [ ]:
db_updater.road_attributes.

In [ ]:
EMPTY_SOURCE = 9999 # don't use for any other source

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
        True, False,  True,  True,  True, False, False, False, False,
        True, False, False, False,  True,  True,  True,  True, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False,  True, False, False,  True,
        True,  True,  True,  True, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False, False,  True, False,  True, False, False, False,
       False, False,  True, False, False, False,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [84]:
empty_old_val = np.isnan(old_val)
empty_old_source = np.isnan(old_source)
empty_new_source = np.isnan(new_source)

In [ ]:
old_source = np.nan_to_num(old_source, nan=EMPTY_SOURCE)
new_source = np.nan_to_num(new_source, nan=EMPTY_SOURCE)
higher_priority_source = new_source < old_source

In [ ]:
old_nonempty_source = (old_source != EMPTY_SOURCE)
new_nonempty_source = (new_source != EMPTY_SOURCE)
old_conf = np.nan_to_num(old_conf, nan=0.0)
new_conf = np.nan_to_num(new_conf, nan=0.0)
higher_conf = (old_nonempty_source & new_nonempty_source & (new_conf >= old_conf))

In [70]:
old_is_empty | higher_priority_source | higher_conf

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [ ]:
old_source = db_updater.road_attributes.loc[id]

osm_id                                                        4705045
oneway                                                            1.0
road_type                                                         2.0
width                                                            10.0
nlanes                                                            4.0
max_speed                                                         NaN
min_speed                                                         NaN
avg_speed           [None, None, None, None, None, None, None, Non...
oneway_source                                                     0.0
road_type_source                                                  0.0
width_source                                                      0.0
nlanes_source                                                     0.0
max_speed_source                                                  NaN
min_speed_source                                                  NaN
avg_speed_source    [None, None, None, None, None, None, None, Non...
oneway_conf                                                      0.95
road_type_conf                                                   0.95
width_conf                                                       0.95
nlanes_conf                                                      0.95
max_speed_conf                                                    NaN
min_speed_conf                                                    NaN
avg_speed_conf      [None, None, None, None, None, None, None, Non...
geometry            LINESTRING (106.8352088 -6.16674829968727, 106...
Name: 282664, dtype: object

In [101]:
db_updater.road_attributes.avg_speed = db_updater.road_attributes.avg_speed.apply(lambda x: np.array(x, dtype=float))
db_updater.road_attributes.avg_speed_conf = db_updater.road_attributes.avg_speed_conf.apply(lambda x: np.array(x, dtype=float))
db_updater.road_attributes.avg_speed_source = db_updater.road_attributes.avg_speed_source.apply(lambda x: np.array(x, dtype=float))
dynamic_pred_metadata.avg_speed_source = dynamic_pred_metadata.avg_speed_source.apply(lambda x: x.astype(float))
dynamic_pred_metadata.avg_speed_conf = dynamic_pred_metadata.avg_speed_conf.apply(lambda x: x.astype(float))

In [102]:
road_attributes = db_updater.road_attributes
def update_temporal_attributes_new(row):
    id = row.name
    old_row = road_attributes.loc[id]

    for col in ['avg_speed']:
        old_val    = old_row[col]
        old_source = old_row[f"{col}_source"]
        old_conf   = old_row[f"{col}_conf"]

        new_val    = row[col]                   # already (672,)
        new_source = row[f"{col}_source"]
        new_conf   = row[f"{col}_conf"]

        empty_old_val = np.isnan(old_val)
        better_source = (new_source < old_source)
        same_source_better_conf = (new_source == old_source) & (new_conf >= old_conf)
        mask = empty_old_val | better_source | same_source_better_conf

        old_val[mask]    = new_val[mask]
        old_source[mask] = new_source[mask]
        old_conf[mask]   = new_conf[mask]

    road_attributes.loc[id] = old_row

tqdm.pandas(desc="Updating temporal road attributes")
dynamic_pred_metadata.progress_apply(update_temporal_attributes_new, axis=1)

Updating temporal road attributes:  16%|█▌        | 83292/512991 [03:06<16:03, 446.16it/s]

KeyboardInterrupt:

In [ ]:
import numpy as np
import pandas as pd

def convert_to_matricies(dynamic_pred_metadata, road_attributes):
    print('1. Align the DataFrames by ID so the matrix rows match perfectly')
    shared_ids = dynamic_pred_metadata.index
    road_attr_subset = road_attributes.loc[shared_ids]

    print('2. Extract entire columns into 2D NumPy arrays')
    # Each resulting array will have a shape of (num_rows, 672)
    old_val = np.stack(road_attr_subset['avg_speed'].values)
    old_source = np.stack(road_attr_subset['avg_speed_source'].values)
    old_conf = np.stack(road_attr_subset['avg_speed_conf'].values)

    new_val = np.stack(dynamic_pred_metadata['avg_speed'].values)
    new_source = np.stack(dynamic_pred_metadata['avg_speed_source'].values)
    new_conf = np.stack(dynamic_pred_metadata['avg_speed_conf'].values)
    
    return old_val, old_source, old_conf, new_val, new_source, new_conf

def update_old_vals(old_val, old_source, old_conf, new_val, new_source, new_conf):
    print('3. Compute the boolean mask across the entire 2D grid instantly')
    empty_old_val = np.isnan(old_val)
    better_source = new_source < old_source
    same_source_better_conf = (new_source == old_source) & (new_conf >= old_conf)

    # Combine conditions into a single master mask
    mask = empty_old_val | better_source | same_source_better_conf

    print('4. Apply changes to the arrays in-place where the mask is True')
    old_val[mask] = new_val[mask]
    old_source[mask] = new_source[mask]
    old_conf[mask] = new_conf[mask]
    
    return old_val, old_source, old_conf

db_handler = DBHandler()
db_handler.connect_to_db()
update_road_ids = dynamic_pred_metadata.index.tolist()
road_attributes = db_handler.roads_from_ids(update_road_ids)
old_val, old_source, old_conf, new_val, new_source, new_conf = convert_to_matricies(dynamic_pred_metadata, road_attributes)
val, source, conf = update_old_vals(old_val, old_source, old_conf, new_val, new_source, new_conf)

1. Align the DataFrames by ID so the matrix rows match perfectly
2. Extract entire columns into 2D NumPy arrays
3. Compute the boolean mask across the entire 2D grid instantly

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [15]:
old_val, old_source, old_conf, new_val, new_source, new_conf

(array([[None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None],
        ...,
        [None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None]], dtype=object),
 array([[None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None],
        ...,
        [None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None]], dtype=object),
 array([[None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None],
        ...,
        [None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None],
        [None, None, None, ..., None, None, None]], dtype=object),
 array([[39.29716873, 39.29716873, 39.29716873, ..., 46.88887405,
         46.88887405, 46.88887405],
        [22.11389732, 22.11389732, 22.11389732, ..., 24.29454803,
         24.29454803, 24.29454803],
        [27.15402794, 27.15402794, 27.15402794, ..., 31.41662025,
         31.41662025, 31.41662025],
        ...,
        [34.76343155, 34.76343155, 34.76343155, ..., 43.81542969,
         43.81542969, 43.81542969],
        [23.48129463, 23.48129463, 23.48129463, ..., 29.61470795,
         29.61470795, 29.61470795],
        [26.18301582, 26.18301582, 26.18301582, ..., 32.26652527,
         32.26652527, 32.26652527]]),
 array([[4, 4, 4, ..., 4, 4, 4],
        [4, 4, 4, ..., 4, 4, 4],
        [4, 4, 4, ..., 4, 4, 4],
        ...,
        [4, 4, 4, ..., 4, 4, 4],
        [4, 4, 4, ..., 4, 4, 4],
        [4, 4, 4, ..., 4, 4, 4]], dtype=object),
 array([[0.8, 0.8, 0.8, ..., 0.8, 0.8, 0.8],
        [0.8, 0.8, 0.8, ..., 0.8, 0.8, 0.8],
        [0.8, 0.8, 0.8, ..., 0.8, 0.8, 0.8],
        ...,
        [0.8, 0.8, 0.8, ..., 0.8, 0.8, 0.8],
        [0.8, 0.8, 0.8, ..., 0.8, 0.8, 0.8],
        [0.8, 0.8, 0.8, ..., 0.8, 0.8, 0.8]], dtype=float32))

In [16]:
old_val  = np.vstack(dynamic_pred_metadata['avg_speed'].values)
old_source = np.vstack(dynamic_pred_metadata['avg_speed_source'].values)
old_conf = np.vstack(dynamic_pred_metadata['avg_speed_conf'].values)

In [17]:
old_val

array([[39.29716873, 39.29716873, 39.29716873, ..., 46.88887405,
        46.88887405, 46.88887405],
       [22.11389732, 22.11389732, 22.11389732, ..., 24.29454803,
        24.29454803, 24.29454803],
       [27.15402794, 27.15402794, 27.15402794, ..., 31.41662025,
        31.41662025, 31.41662025],
       ...,
       [34.76343155, 34.76343155, 34.76343155, ..., 43.81542969,
        43.81542969, 43.81542969],
       [23.48129463, 23.48129463, 23.48129463, ..., 29.61470795,
        29.61470795, 29.61470795],
       [26.18301582, 26.18301582, 26.18301582, ..., 32.26652527,
        32.26652527, 32.26652527]])

In [ ]:




# print('5. Convert modified matrices back into Python lists to update the DataFrame')
# (We wrap them back in individual lists so Pandas can store them in cell objects)
# Convert the 2D matrix back into a 1D list of individual arrays/lists
# road_attributes.loc[shared_ids, 'avg_speed'] = [row for row in old_val]
# road_attributes.loc[shared_ids, 'avg_speed_source'] = [row for row in old_source]
# road_attributes.loc[shared_ids, 'avg_speed_conf'] = [row for row in old_conf]

1. Align the DataFrames by ID so the matrix rows match perfectly
2. Extract entire columns into 2D NumPy arrays
3. Compute the boolean mask across the entire 2D grid instantly
4. Apply changes to the arrays in-place where the mask is True
5. Convert modified matrices back into Python lists to update the DataFrame

ValueError: Must have equal len keys and value when setting with an ndarray

In [ ]:
db_handler = DBHandler()
db_handler.connect_to_db()
db_updater = DBUpdater(db_handler)

In [ ]:
id_list = shared_ids.tolist()

db_updater = DBUpdater(db_handler)

In [ ]:
db_handler.update_dynamic_attributes(old_val, old_source, old_conf, id_list)

Connecting to Database using psycopg2
Set Up Chunking
Create High-Performance UNLOGGED Staging Table

In [136]:
old_val[0][0] = np.nan

In [138]:
str(old_val[0].tolist())

'[nan, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508, 9.52993076122449, 8.713604350016404, 9.595946087894113, 39.29716873168945, 9.252570646833147, 38.240020751953125, 38.240020751953125, 38.240020751953125, 10.389615522531361, 7.957000000000001, 7.242214, 8.579424634251241, 40.179359436035156, 10.245714285714286, 10.430869517119035, 12.448333333333332, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 11.817777777777778, 49.44483947753906, 49.44483947753906, 10.472500085830688, 9.109925171887433, 10.50179537646274, 8.107272624969482, 10.87142857142857, 4.523651411764706, 11.173076923076923, 9.652666439999999, 10.791851851851852, 10.163242883682251, 8.853928571428572, 9.006978324053955, 11.029999666666667, 10.862, 40.179359436035156, 11.149999904632569, 11.163849081984576, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 9.294374942779541, 10.378812838235294, 9.345000147819519, 11.499999926640438, 10.64097892567359, 17.06555567847358, 12.621141624450683, 38.240020751953125, 9.547646766666666, 14.722500085830688, 8.765624964776357, 8.353333393732706, 35.73617172241211, 9.26908302173913, 10.575555483500164, 40.179359436035156, 11.083478222722592, 10.862307695242075, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 9.077016227520534, 11.199047662644158, 7.809028979976654, 39.29716873168945, 6.6379999876022335, 11.222692342904898, 7.765882352941177, 38.240020751953125, 11.625217313351838, 8.296734686092455, 8.01894922090867, 4.389039153925863, 9.543000022888183, 7.589385170172214, 9.104615431565504, 0.6154566216577678, 7.764163817284342, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 9.81440005493164, 39.29716873168945, 39.29716873168945, 9.556800022125245, 7.897777822282579, 14.066758125, 11.207611548540388, 4.0444387196948846, 8.57075688065389, 35.73617172241211, 7.628628999762432, 6.438518349822574, 8.599069755909055, 9.150980366351558, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 11.58, 49.44483947753906, 43.639320373535156, 11.67142915725708, 10.187905041214556, 43.639320373535156, 11.021428571428572, 39.76142883300781, 9.793581027685983, 9.837961685823755, 7.076394910782296, 8.452650867684152, 8.155977317647059, 39.12522506713867, 4.103606877595726, 8.81741936837473, 11.483353181318803, 41.41552734375, 48.39216613769531, 48.39216613769531, 11.492727366360752, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 11.681268168148643, 43.639320373535156, 43.639320373535156, 8.634980495582193, 0.2334765573359375, 9.936499987602234, 9.45621132850647, 10.320714285714287, 10.367358445632645, 11.09769117143419, 39.12522506713867, 10.21407992828139, 8.864247935714285, 9.051333333333334, 7.6387499670187635, 12.635999965667725, 41.41552734375, 12.200909094376998, 48.39216613769531, 48.39216613769531, 48.39216613769531, -1.0, 46.88887405395508, 46.88887405395508, 11.406363660638982, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508]'

In [139]:
str(old_val[0].tolist()).replace("[", "{").replace("]", "}")

'{nan, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508, 9.52993076122449, 8.713604350016404, 9.595946087894113, 39.29716873168945, 9.252570646833147, 38.240020751953125, 38.240020751953125, 38.240020751953125, 10.389615522531361, 7.957000000000001, 7.242214, 8.579424634251241, 40.179359436035156, 10.245714285714286, 10.430869517119035, 12.448333333333332, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 11.817777777777778, 49.44483947753906, 49.44483947753906, 10.472500085830688, 9.109925171887433, 10.50179537646274, 8.107272624969482, 10.87142857142857, 4.523651411764706, 11.173076923076923, 9.652666439999999, 10.791851851851852, 10.163242883682251, 8.853928571428572, 9.006978324053955, 11.029999666666667, 10.862, 40.179359436035156, 11.149999904632569, 11.163849081984576, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 9.294374942779541, 10.378812838235294, 9.345000147819519, 11.499999926640438, 10.64097892567359, 17.06555567847358, 12.621141624450683, 38.240020751953125, 9.547646766666666, 14.722500085830688, 8.765624964776357, 8.353333393732706, 35.73617172241211, 9.26908302173913, 10.575555483500164, 40.179359436035156, 11.083478222722592, 10.862307695242075, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 9.077016227520534, 11.199047662644158, 7.809028979976654, 39.29716873168945, 6.6379999876022335, 11.222692342904898, 7.765882352941177, 38.240020751953125, 11.625217313351838, 8.296734686092455, 8.01894922090867, 4.389039153925863, 9.543000022888183, 7.589385170172214, 9.104615431565504, 0.6154566216577678, 7.764163817284342, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 9.81440005493164, 39.29716873168945, 39.29716873168945, 9.556800022125245, 7.897777822282579, 14.066758125, 11.207611548540388, 4.0444387196948846, 8.57075688065389, 35.73617172241211, 7.628628999762432, 6.438518349822574, 8.599069755909055, 9.150980366351558, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 11.58, 49.44483947753906, 43.639320373535156, 11.67142915725708, 10.187905041214556, 43.639320373535156, 11.021428571428572, 39.76142883300781, 9.793581027685983, 9.837961685823755, 7.076394910782296, 8.452650867684152, 8.155977317647059, 39.12522506713867, 4.103606877595726, 8.81741936837473, 11.483353181318803, 41.41552734375, 48.39216613769531, 48.39216613769531, 11.492727366360752, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 11.681268168148643, 43.639320373535156, 43.639320373535156, 8.634980495582193, 0.2334765573359375, 9.936499987602234, 9.45621132850647, 10.320714285714287, 10.367358445632645, 11.09769117143419, 39.12522506713867, 10.21407992828139, 8.864247935714285, 9.051333333333334, 7.6387499670187635, 12.635999965667725, 41.41552734375, 12.200909094376998, 48.39216613769531, 48.39216613769531, 48.39216613769531, -1.0, 46.88887405395508, 46.88887405395508, 11.406363660638982, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 39.29716873168945, 39.29716873168945, 39.29716873168945, 39.29716873168945, 38.240020751953125, 38.240020751953125, 38.240020751953125, 38.240020751953125, 35.73617172241211, 35.73617172241211, 35.73617172241211, 35.73617172241211, 40.179359436035156, 40.179359436035156, 40.179359436035156, 40.179359436035156, 48.85234451293945, 48.85234451293945, 48.85234451293945, 48.85234451293945, 49.44483947753906, 49.44483947753906, 49.44483947753906, 49.44483947753906, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508, 43.639320373535156, 43.639320373535156, 43.639320373535156, 43.639320373535156, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.76142883300781, 39.12522506713867, 39.12522506713867, 39.12522506713867, 39.12522506713867, 41.41552734375, 41.41552734375, 41.41552734375, 41.41552734375, 48.39216613769531, 48.39216613769531, 48.39216613769531, 48.39216613769531, 46.88887405395508, 46.88887405395508, 46.88887405395508, 46.88887405395508}'

In [111]:
old_source.astype(int)

/tmp/ipykernel_858428/97585962.py:1: RuntimeWarning: invalid value encountered in cast
  old_source.astype(int)

array([[4, 4, 4, ..., 4, 4, 4],
       [4, 4, 4, ..., 4, 4, 4],
       [4, 4, 4, ..., 4, 4, 4],
       ...,
       [4, 4, 4, ..., 4, 4, 4],
       [4, 4, 4, ..., 4, 4, 4],
       [4, 4, 4, ..., 4, 4, 4]])

In [109]:
# Convert rows to plain Python tuples or a tuple of arrays to block 2D unpacking
road_attributes.loc[shared_ids, 'avg_speed'] = [tuple(row) for row in old_val]
road_attributes.loc[shared_ids, 'avg_speed_source'] = [tuple(row) for row in old_source]
road_attributes.loc[shared_ids, 'avg_speed_conf'] = [tuple(row) for row in old_conf]

ValueError: Must have equal len keys and value when setting with an ndarray

In [107]:
len(shared_ids)

512991

In [99]:
db_handler = DBHandler()
db_handler.connect_to_db()
db_updater = DBUpdater(db_handler)
db_updater.update_database_new(temporal_attr=dynamic_pred_metadata)

Updating temporal road attributes:   0%|          | 1/512991 [00:00<15:24:50,  9.24it/s]

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [100]:
db_updater.road_attributes.iloc[0].avg_speed

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Decimal('9.753333250681559'),
 Decimal('8.15157103437232'),
 Decimal('8.550000190734863'),
 Decimal('6.309426664874268'),
 Decimal('8.916269232818603'),
 Decimal('7.66'),
 None,
 None,
 None,
 Decimal('15.591594875'),
 Decimal('3.8010948545454544'),
 None,
 Decimal('13.560872'),
 Decimal('11.164999961853027'),
 None,
 None,
 None,
 Decimal('12.382857050214495'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Decimal('13.926666577657064'),
 Decimal('11.970000267028809'),
 None,
 Decimal('12.52'),
 Decimal('0.0'),
 None,
 Decimal('10.530714285714286'),
 None,
 None,
 None,
 None,
 Decimal('12.135999870300292'),
 Decimal('8.843075046185302'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Decimal('8.010555585225424'),
 Decimal('11.365093630161383'),
 None,
 None,
 Decimal('11.995000123977661'),
 Decimal('11.583333333333334'),
 None,
 Decimal('8.48674'),
 None,
 None,
 None,
 Decimal('12.402575083333332'),
 None,
 None,
 Decimal('13.25333340962728'),
 None,
 None,
 None,
 Decimal('13.32230780674861'),
 None,
 None,
 None,
 None,
 None,
 Decimal('11.742000198364257'),
 Decimal('10.539999961853027'),
 None,
 Decimal('-1.0'),
 Decimal('9.25845014090909'),
 None,
 None,
 None,
 Decimal('9.721111123826768'),
 Decimal('11.649999895095824'),
 Decimal('9.547999997456868'),
 None,
 Decimal('11.974469884615385'),
 Decimal('14.64049997329712'),
 Decimal('15.262500047683716'),
 None,
 Decimal('16.200000762939453'),
 None,
 None,
 None,
 None,
 None,
 Decimal('13.44814725'),
 Decimal('12.89'),
 Decimal('11.549386142857141'),
 Decimal('12.17'),
 Decimal('11.027142797197616'),
 Decimal('8.771306742960611'),
 Decimal('7.84333340326945'),
 None,
 Decimal('5.6226666666666665'),
 None,
 Decimal('10.977500054041544'),
 None,
 None,
 None,
 None,
 None,
 Decimal('11.101999982198079'),
 None,
 None,
 None,
 None,
 Decimal('18.25'),
 None,
 None,
 Decimal('15.38968'),
 None,
 None,
 None,
 Decimal('10.624749982357026'),
 None,
 None,
 Decimal('5.89511345'),
 None,
 None,
 Decimal('9.16558830878314'),
 None,
 Decimal('11.01599998474121'),
 None,
 Decimal('12.708571297781807'),
 Decimal('7.340000152587891'),
 None,
 None,
 Decimal('14.62985334375'),
 None,
 None,
 Decimal('8.408750027418137'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Decimal('7.96571427481515'),
 Decimal('6.968124950408935'),
 None,
 Decimal('6.093076944351196'),
 Decimal('6.74933336575826'),
 Decimal('12.487495675'),
 Decimal('5.926666679836455'),
 None,
 Decimal('12.057789227272728'),
 None,
 None,
 None,
 Decimal('13.609999656677246'),
 Decimal('14.088181715085671'),
 Decimal('16.29'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [ ]:
db_updater.update_database_new(static_attr=static_pred_metadata, temporal_attr=dynamic_pred_metadata)

In [14]:
dynamic_pred_metadata

,osm_id,avg_speed,avg_speed_source,avg_speed_conf
282664,4705045,"[39.29716873168945, 39.29716873168945, 39.2971...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, ..."
282663,4705043,"[22.1138973236084, 22.1138973236084, 22.113897...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, ..."
282665,4705046,"[27.154027938842773, 27.154027938842773, 27.15...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, ..."
282665,4705046,"[38.18931579589844, 38.18931579589844, 38.1893...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, ..."
282664,4705045,"[33.255165100097656, 33.255165100097656, 33.25...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, ..."
...,...,...,...,...
212245832,1323780385,"[36.438865661621094, 36.438865661621094, 36.43...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, ..."
211625167,1318113065,"[23.50935935974121, 23.50935935974121, 23.5093...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, ..."
211603264,1317986765,"[34.763431549072266, 34.763431549072266, 34.76...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, ..."
211553340,1317609752,"[23.481294631958008, 23.481294631958008, 23.48...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, ..."
211358975,1316224461,"[26.183015823364258, 26.183015823364258, 26.18...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, ..."

In [38]:
import geopandas as gpd
edges_path  = os.path.join('./data/raw_data', f"jakarta_edges.parquet")
edges = gpd.read_parquet(edges_path)

In [39]:
edges

,source,target,pgr_id,osm_id,oneway,road_type,nlanes,width,length,geometry,max_speed,min_speed
0,52860,7874,98,4705045,1.0,2.0,4.0,10.000000,56.769815,"LINESTRING (106.84 -6.1673, 106.84 -6.1677)",NaN,NaN
1,30445,87959,212,4705043,1.0,2.0,1.0,4.000000,293.579384,"LINESTRING (106.84 -6.1678, 106.84 -6.1679, 10...",NaN,NaN
2,1359,102290,213,4705046,1.0,2.0,2.0,6.000000,12.779379,"LINESTRING (106.84 -6.1681, 106.84 -6.1682)",NaN,NaN
3,47817,58347,38783,4705046,1.0,2.0,2.0,6.000000,76.590609,"LINESTRING (106.84 -6.1669, 106.84 -6.167, 106...",NaN,NaN
4,7874,92444,47381,4705045,1.0,2.0,4.0,10.000000,28.160970,"LINESTRING (106.84 -6.1677, 106.84 -6.168)",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
512986,554572,3126680,4265252,1323780385,1.0,3.0,1.0,7.670237,5.210311,"LINESTRING (106.84 -6.1815, 106.84 -6.1815)",NaN,NaN
512987,562231,3126704,4265281,1318113065,0.0,1.0,1.0,2.319501,28.838543,"LINESTRING (106.76 -6.1815, 106.76 -6.1814, 10...",NaN,NaN
512988,1705639,3126735,4265318,1317986765,0.0,0.0,0.0,3.734968,27.817565,"LINESTRING (106.76 -6.1698, 106.76 -6.1697)",NaN,NaN
512989,1590678,3126756,4265341,1317609752,0.0,0.0,1.0,3.889288,30.114436,"LINESTRING (106.69 -6.1917, 106.69 -6.1917, 10...",NaN,NaN
512990,1352387,3126785,4265370,1316224461,1.0,1.0,1.0,3.998764,12.209148,"LINESTRING (106.76 -6.1623, 106.76 -6.1623, 10...",NaN,NaN